### ISSUE TITLE
Most nether audio sources are not working.

### ISSUE THREAD

**Issue by Matlauk** [jrbudda/Vivecraft_116#10]
Breaking most blocks in the nether does not produce a sound. Ambient noises don't play. Piglins don't make any noise.

**Comment by MJLaukala** [comment]
I did more testing. Seems to only be an issue when debugging (Eclipse). The test build seemed to work fine and even installing the exe from build.bat worked so i really have no idea why it doesn't work when debugging or even just run in Eclipse.

**Comment by Techjar** [comment]
Sounds like your asset index isn't up to date.

**Comment by MJLaukala** [comment]
How do I check/fix that? It happens on a fresh install.bat of the current master branch.
