### ISSUE TITLE
[1.16.5] Crash upon creating new world

### ISSUE THREAD

**Issue by Salamance73** [jrbudda/Vivecraft_116#100]
I cant seem to create a new world without it giving me a 
_"Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world"_
I followed the instructions for using vivecraft with multimc, the only thing Ive done thats slightly different (but still supported) is change the forge version to 36.1.3. When that didnt work I tried to lower the forge version to 36.1.26 with no difference. 
Here's the crashlog: [https://pastebin.com/YupcduKR](url)

**Comment by Espergium** [comment]
Try a brand new world? It's throwing a no such method error.

**Comment by Salamance73** [comment]
like i said, im making a new world

**Comment by Salamance73** [comment]
I think I might have accidentally downloaded the 1.16.4 version of the vivecraft installer, the 1.16.5 seems to have let me go through with world creation. Thanks for the quick response.
