### ISSUE TITLE
Steam VR crashes with TextureUsesUnsupportedFormat

### ISSUE THREAD

**Issue by matejdro** [jrbudda/Vivecraft_116#102]
After couple of minutes of playing Vivecraft, it will crash the whole Steam VR.

Debug log:
[debug.log](https://github.com/jrbudda/Vivecraft_116/files/6643384/debug.log)

Only clue from logs that I could find are these two lines:

```
[13Jun2021 08:28:34.268] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Texture submission error: Left/Right TextureUsesUnsupportedFormat:/TextureUsesUnsupportedFormat:
[13Jun2021 08:28:34.442] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Texture submission error: Left/Right TextureUsesUnsupportedFormat:/TextureUsesUnsupportedFormat:
```

I'm running ViveCraft 1.15.4 and SteamVR 1.18.1 Beta

**Comment by Techjar** [comment]
This look like a SteamVR problem, not a Vivecraft problem. The texture submission error must be spurious.

**Comment by matejdro** [comment]
Yeah it looks like SteamVR problem. It only happens with ViveCraft, so I made an issue just in case. From what I see, this error always precedes the crash, so the correlation is pretty high. I wouldn't count it out as spurious.

**Comment by Techjar** [comment]
Minecraft seems to have a tendency to crash VR runtimes on weaker hardware.

**Comment by matejdro** [comment]
I have Ryzen 3700X so that is almost certainly not the case.

**Comment by Techjar** [comment]
Hmm, okay. I would look over the incompatible software list then, could be something in there that you happen to have installed on your system.

https://minecrafthopper.net/help/known-incompatible-software/

**Comment by Techjar** [comment]
Also, if you happen to have Razer Cortex, its game booster is known to nuke SteamVR.

**Comment by matejdro** [comment]
Nothing from that list (Discord is installed, but overlay disabled).

**Comment by Techjar** [comment]
Can you produce the crash again and upload the logs I mentioned before?

**Comment by matejdro** [comment]
Issue appears to be caused by the Windows Mixed Reality for SteamVR 1.3.6. Sorry for bothering you.

**Comment by Techjar** [comment]
You're all good, we like to know about issues like this so we can help people as best as possible. Do you have more information about what exactly the problem with WMR for SteamVR is?

**Comment by matejdro** [comment]
Looking at comments for the new Windows Mixed Reality for SteamVR 1.3.6 Beta, a lot of people seem to experience crashes. The fix is simple, just rollback from beta to stable.

Hopefully they will fix that before it goes stable though.
