### ISSUE TITLE
not sure what's crashing 

### ISSUE THREAD

**Issue by Toonlink264** [jrbudda/Vivecraft_116#104]
i was trying to use Vivecraft with Enigmatica 6 Version 0.5.0 and something crashes, the pack runs fine when not using Vivecraft but as soon as i try it fails. it won't give a crash log only latest
[latest.log](https://github.com/jrbudda/Vivecraft_116/files/6682190/latest.log)

**Comment by Techjar** [comment]
Ars Nouveau has a conflict with Vivecraft. There's a workaround on the compatibility sheet, if you're somewhat technically inclined: http://www.vivecraft.org/forge-mod-compatibility/

**Comment by Toonlink264** [comment]
i went to that page and for some reason my screen is cutting off that line of text

**Comment by Techjar** [comment]
Fixed.Alright I fixed the sheet.
