### ISSUE TITLE
Install.bat hanging on Decompiling

### ISSUE THREAD

**Issue by jaydengamble6** [jrbudda/Vivecraft_116#105]
It's just stuck there and it won't do what it says its doing after a while, CPU usage is is above 90% the whole time and no disk usage the folder of SRC is around 600MB (before running install.bat it was around 50MB) and I'm using the latest source code.
Any help is appreciated.

**Comment by Techjar** [comment]
Are you trying to play Vivecraft or develop for it? Cause that isn't how to actually install it for playing, install.bat sets up the dev environment. Installers for play are on the releases page: https://github.com/jrbudda/Vivecraft_116/releases

If you're actually trying to develop, just have some patience; the decompile takes a very long time, depending on your CPU of course.

**Comment by jaydengamble6** [comment]
Playing, I thought the source code might have an updated version for playing so I tried to do that, I thought to try that because Vivecraft crashes on loading a world with a [TARDIS Mod](https://gitlab.com/Spectre0987/TardisMod-1-14)
