### ISSUE TITLE
Issue With Loading into multiplayer and singleplayer

### ISSUE THREAD

**Issue by KingDeku86** [jrbudda/Vivecraft_116#108]
Hello, I am having an issue on 1.12.2 Forge with the mods it keeps giving me this error (below) [PS. I also have 7gb of ram allocated]
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Exit Code: -1
I have no idea how to fix it and i will post my crash report below, SEND HELP!!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.15.0.1_Forge_1.12.jar)
  Vivecraft Forge Extensions Core (VivecraftForgeExtensions-1.12.2-0.2.4.12.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.16.0_Forge_1.12.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/24/21 6:45 AM
Description: Unexpected error

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at xaero.common.core.XaeroMinimapCore.beforeIngameGuiRender(XaeroMinimapCore.java:163)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:108)
	at net.minecraft.client.renderer.EntityRenderer.drawFramebuffer(EntityRenderer.java:4107)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1612)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:647)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at xaero.common.core.XaeroMinimapCore.beforeIngameGuiRender(XaeroMinimapCore.java:160)
	... 16 more
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.EntityRenderer.func_78467_g(EntityRenderer.java:1012)
	at net.minecraft.client.renderer.EntityRenderer.setupCameraTransform(EntityRenderer.java:1113)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:1043)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at xaero.common.core.XaeroMinimapCore.beforeIngameGuiRender(XaeroMinimapCore.java:163)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:108)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['KingDeku86'/585, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 2 total; [GCEntityClientPlayerMP['KingDeku86'/585, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/13, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/13, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:3667)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:676)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.vivecraft.main.VivecraftMain.main(VivecraftMain.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2062275280 bytes (1966 MB) / 4241489920 bytes (4045 MB) up to 7427063808 bytes (7083 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -Xms4G -XX:+UseParallelGC -XX:ParallelGCThreads=3 -XX:MaxGCPauseMillis=3 -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                           | Version                 | Source                                            | Signature                                |
	|:------ |:---------------------------- |:----------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                    | 1.12.2                  | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                          | 9.42                    | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                          | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                        | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore                |                         | minecraft.jar                                     | None                                     |
	| LCHIJA | vivecraftforgeextensionscore | 0.2.4.12                | minecraft.jar                                     | None                                     |
	| LCHIJA | xaerominimap_core            | 1.12.2-1.0              | minecraft.jar                                     | None                                     |
	| LCHIJA | xaeroworldmap_core           | 1.12.2-1.0              | minecraft.jar                                     | None                                     |
	| LCHIJA | openmodscore                 | 0.12.2                  | minecraft.jar                                     | None                                     |
	| LCHIJA | techguns_core                | 1.12.2-1.0              | minecraft.jar                                     | None                                     |
	| LCHIJA | mercurius_updater            | 1.0                     | MercuriusUpdater-1.12.2.jar                       | None                                     |
	| LCHIJA | armortoolsores               | 1.7.3                   | 1.7.3-1.12.2ATOp.jar                              | None                                     |
	| LCHIJA | securitycraft                | v1.8.23.2               | [1.12.2]+SecurityCraft+v1.8.23.2.jar              | None                                     |
	| LCHIJA | aether_legacy                | 1.5.3.2                 | aether-1.12.2-v1.5.3.2.jar                        | None                                     |
	| LCHIJA | bettermineshafts             | 1.12.2-2.2.1            | BetterMineshaftsForge-1.12.2-2.2.1.jar            | None                                     |
	| LCHIJA | biomesoplenty                | 7.0.1.2444              | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar     | None                                     |
	| LCHIJA | byg                          | 1.7.1                   | BiomesYouGo1.7.1.jar                              | None                                     |
	| LCHIJA | bonsaitrees                  | 1.1.4                   | bonsaitrees-1.1.4-b170.jar                        | None                                     |
	| LCHIJA | buildinggadgets              | 2.8.4                   | BuildingGadgets-2.8.4.jar                         | None                                     |
	| LCHIJA | caves_and_cliffs             | 1.0.9                   | CC(FG1.12.2)+1.0.9.jar                            | None                                     |
	| LCHIJA | chiselsandbits               | 14.33                   | chiselsandbits-14.33.jar                          | None                                     |
	| LCHIJA | ichunutil                    | 7.2.0                   | iChunUtil-1.12.2-7.2.0.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | clef                         | 7.1.0                   | Clef-1.12.2-7.1.0.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | craftablenametag             | 1.0.0                   | CN+(MC+1.12.2).jar                                | None                                     |
	| LCHIJA | ctm                          | MC1.12.2-1.0.2.31       | CTM-MC1.12.2-1.0.2.31.jar                         | None                                     |
	| LCHIJA | dimdoors                     | 1.12.2-3.1.2+UNOFFICIAL | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar      | None                                     |
	| LCHIJA | elevatorid                   | 1.3.14                  | ElevatorMod-1.12.2-1.3.14.jar                     | None                                     |
	| LCHIJA | extrautils2                  | 1.0                     | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCHIJA | cfm                          | 6.3.1                   | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| LCHIJA | futureminecraf               | 1.3.1                   | FutureVersions+v1.3.1.jar                         | None                                     |
	| LCHIJA | galacticraftcore             | 4.0.2.280               | GalacticraftCore-1.12.2-4.0.2.280.jar             | None                                     |
	| LCHIJA | galacticraftplanets          | 4.0.2.280               | Galacticraft-Planets-1.12.2-4.0.2.280.jar         | None                                     |
	| LCHIJA | gottschcore                  | 1.14.0                  | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar    | None                                     |
	| LCHIJA | waila                        | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHIJA | instahouses                  | 1.0                     | instahouses-1.12.2-1.1.1.jar                      | None                                     |
	| LCHIJA | inventorypets                | 2.0.15                  | inventorypets-1.12-2.0.15.jar                     | None                                     |
	| LCHIJA | ironbackpacks                | 1.12.2-3.0.8-12         | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCHIJA | ironchest                    | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHIJA | jei                          | 4.16.1.302              | jei_1.12.2-4.16.1.302.jar                         | None                                     |
	| LCHIJA | lockdown_additions           | 1.0.4                   | LA_1.12.2-1.0.5.1.jar                             | None                                     |
	| LCHIJA | locks                        | 2.5.1                   | locks-1.12.2-2.5.1.jar                            | None                                     |
	| LCHIJA | raycore                      | 3.2.1.0                 | raycore-1.12.2-3.2.1.0.jar                        | None                                     |
	| LCHIJA | mario2                       | 3.2.0.2                 | mario2-1.12.2-3.2.0.2.jar                         | None                                     |
	| LCHIJA | mca                          | 6.1.0                   | MCA-1.12.2-6.1.0-universal.jar                    | None                                     |
	| LCHIJA | morph                        | 7.2.0                   | Morph-1.12.2-7.2.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | naturescompass               | 1.8.5                   | NaturesCompass-1.12.2-1.8.5.jar                   | None                                     |
	| LCHIJA | openmods                     | 0.12.2                  | OpenModsLib-1.12.2-0.12.2.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                   | 1.8.1                   | OpenBlocks-1.12.2-1.8.1.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | placeableitems               | 3.3                     | placeableitems-3.3.jar                            | None                                     |
	| LCHIJA | portalgun                    | 7.1.0                   | PortalGun-1.12.2-7.1.0.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | scootys_scp_mod              | 1.5                     | SCP+Lockdown+Heavy+Expansion+1.5.1.jar            | None                                     |
	| LCHIJA | scp_obscure                  | 0.5                     | SCP+Obscure+v0.5.jar                              | None                                     |
	| LCHIJA | scp                          | 2.4.0                   | SCP_Lockdown-1.12.2-2.4.0-hotfix.jar              | None                                     |
	| LCHIJA | scpfsiteclassesarmormod      | 1.0.0                   | scpfsite19classes-1.0.0-SNAPSHOT.jar              | None                                     |
	| LCHIJA | scple                        | 1.0                     | scple-1.0.jar                                     | None                                     |
	| LCHIJA | simpleminingdrills           | 1.4.0                   | simpleminingdrills+1.12.2.jar                     | None                                     |
	| LCHIJA | sit                          | v1.3                    | sit-1.12.2-v1.3.jar                               | None                                     |
	| LCHIJA | techguns                     | 2.0.2.0                 | techguns-1.12.2-2.0.2.0_pre3.2.jar                | None                                     |
	| LCHIJA | thehunt                      | 0.4.0                   | thehunt-0.4.0.jar                                 | c684c7b0d96abf507f1edc4dec8e191b14c0b166 |
	| LCHIJA | treasure2                    | 1.12.1                  | Treasure2-mc1.12.2-f14.23.5.2768-v1.12.1.jar      | None                                     |
	| LCHIJA | treechopper                  | 1.2.4                   | TreeChopper-1.12.2-1.2.4.jar                      | None                                     |
	| LCHIJA | trumpetskeleton              | 1.12-1.0.2.1            | trumpetskeleton-1.12-1.0.2.1.jar                  | None                                     |
	| LCHIJA | twilightforest               | 3.11.1021               | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
	| LCHIJA | vivecraftforgeextensions     | 0.2.4.12                | VivecraftForgeExtensions-1.12.2-0.2.4.12.jar      | fd9d04044a812606cd8b960f9512e4e30cd25710 |
	| LCHIJA | gvc                          | 1.2.5                   | Voice+Chat+Reloaded-1.2.5.jar                     | None                                     |
	| LCHIJA | wailaharvestability          | 1.1.12                  | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |
	| LCHIJA | worldedit                    | 6.1.10-SNAPSHOT         | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCHIJA | xaerominimap                 | 21.15.0.1               | Xaeros_Minimap_21.15.0.1_Forge_1.12.jar           | None                                     |
	| LCHIJA | xaeroworldmap                | 1.16.0                  | XaerosWorldMap_1.16.0_Forge_1.12.jar              | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.15.0.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
Vivecraft Forge Extensions Core (VivecraftForgeExtensions-1.12.2-0.2.4.12.jar)
  com.techjar.vivecraftforge.core.asm.ClassTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.16.0_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011' Renderer: 'Radeon RX 580 Series'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Launched Version: vivecraft-1.12.2-jrbudda-11-r5-forge
	LWJGL: 2.9.4
	OpenGL: Radeon RX 580 Series GL version 4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by Espergium** [comment]
Remove Xaero minimap.

`Description: Unexpected error

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at xaero.common.core.XaeroMinimapCore.beforeIngameGuiRender(XaeroMinimapCore.java:163)`
