### ISSUE TITLE
Could FidelityFX Super Resolution be implemented?

### ISSUE THREAD

**Issue by Soggy-Pancake** [jrbudda/Vivecraft_116#109]
I've seen massive performance gains in vr with a modified open_vr dll  with fidelityFX included (https://github.com/fholger/openvr_fsr) Is it possible to add fsr to vivecraft?

**Comment by JadianRadiator** [comment]
yes it can.
I don't know if it would be different on 32 bit,
but the 64bit location of Vivecraft's openvr_api.dll is at %appdata%\.minecraft\openvr\win64\

**Comment by Techjar** [comment]
No.
