### ISSUE TITLE
Unable to download forge. What to do?

### ISSUE THREAD

**Issue by Lucas210106** [jrbudda/Vivecraft_116#112]
When trying to use the installer with forge (Since I wanna play modded vc) it throws up an error. Said error is this: 
[link redacted, use a different image upload service please]
How do I fix it?

**Comment by Lucas210106** [comment]
And yes, I checked other versions, none work

**Comment by jrbudda** [comment]
all links should be fixed, any remaining problems with latest versions must be user-side problems
