### ISSUE TITLE
Oculus Quest 2.

### ISSUE THREAD

**Issue by ghost** [jrbudda/Vivecraft_116#114]
Does This Project work for Oculus Quest 2 with Oculus Link? I Have steamvr open and have ViveCraft 1.16.5 installed but, it keeps saying 
![image](https://user-images.githubusercontent.com/90421253/136873077-84bfe583-d911-4042-9209-a8c502c25ad9.png)
help please

**Comment by SkyIsntFound** [comment]
![image](https://user-images.githubusercontent.com/90421253/137036853-3998e76f-ab80-4037-867b-0cbe7288064f.png)

**Comment by Techjar** [comment]
Did you by chance disable the page file in Windows?
