### ISSUE TITLE
VR Server Init Failed (300)

### ISSUE THREAD

**Issue by Kavk1n** [jrbudda/Vivecraft_116#117]
Hi! I'm using oculus quest 2 with Airlink. It worked perfectly fine about three days ago, but now all of a sudden I can't launch the game. Tried reinstalling steamvr and the Vivecraft aswell, didn't work. What should I do?

**Comment by Techjar** [comment]
Try reinstalling oculus?

**Comment by jrbudda** [comment]
not vivecraft related
