### ISSUE TITLE
Incompatible with Magnesium mod

### ISSUE THREAD

**Issue by cpm9** [jrbudda/Vivecraft_116#118]
https://www.curseforge.com/minecraft/mc-mods/sodium-reforged

Game won't launch. Magnesium is an optifine alternative that performs much better, however, its incompatible with optifine. I believe vivecraft is bundeled with optifine. So a fix may be as easy as making a version of vivecraft that doesn't include optifine? Thanks

**Comment by Espergium** [comment]
It's built ON optifine. Switching it out means changing vivecraft entirely.

**Comment by jrbudda** [comment]
yea not doing this, not on 1.16 anyway
