### ISSUE TITLE
Blockbench Offsets still non-functional

### ISSUE THREAD

**Issue by InfernoDigital** [jrbudda/Vivecraft_116#12]
I'm currently working in Blockbench making 3D model packs for Minecraft and Vivecraft and although apparently offsets have been supported in the most recent versions of Vivecraft models are still rotated at odd angles and scaled wildly differently in Vivecraft than in Vanilla minecraft. I'll give my two packs as proof

The Infinity Blade Pack - https://www.planetminecraft.com/texture-pack/the-infinity-blade-pack/

and

The Paintball PVP Pack - https://www.planetminecraft.com/texture-pack/paintball-pvp-pack-desktop-variant/

using the json offsets that Blockbench creates, vanilla minecraft rotates, positions and scales the models perfectly in all views (especially the first person view, which I believe is what Vivecraft is supposed to use) .

https://imgur.com/gallery/UcJ8IIr

https://imgur.com/gallery/YVsdXK2

however in Vivecraft these same packs are usually at least 180 degrees off and massively incorrectly scaled (either two big or too small)

https://imgur.com/gallery/3rVRj0m

Budda, if at some point you need to rip open these jsons to figure out why they aren't scaling and rotating correctly I give you full permission to, cause I'd really love to make more packs for use in Vivecraft.

But right now without a lot of extra work on the pack-maker's end it's very difficult to make packs with models that work in Vivecraft. I had to remake the original "infinity blade pack" model from scratch at the right angle for vr which was quite difficult and I can't put that much time into newer versions, but I'd love for these packs' offsets to work somehow. 

Thanks for all the hard work budda! You rock!

**Comment by jrbudda** [comment]
this whole thing needs a re-do
