### ISSUE TITLE
Modpack Crashing Enigmatica 6

### ISSUE THREAD

**Issue by vladdeda** [jrbudda/Vivecraft_116#120]
Anytime I launch the modpack on forge 36.2.8 (no vr version works fine) with VR mode the game loads a few mods then crashes giving error 0. Here is log. Any ideas?

I'm looking through log for an offending mod, haven't found anything yet.

https://pastebin.com/CMXjRM8w

**Comment by fayer3** [comment]
use the selene version lined here: http://www.vivecraft.org/forge-mod-compatibility/

**Comment by vladdeda** [comment]
It got further in loading, but threw up another error and crashed. Actually generated a crash log this time.

https://pastebin.com/g2rx5Zit

**Comment by Techjar** [comment]
Remove entity culling and install this version instead https://www.curseforge.com/minecraft/mc-mods/entityculling

**Comment by vladdeda** [comment]
That fixed it, thank you!
