### ISSUE TITLE
Vivecraft not working with forge 36.2.4

### ISSUE THREAD

**Issue by cgdude1** [jrbudda/Vivecraft_116#121]
I've been trying to add vivecraft to the modpack Create: Above and Beyond and initially was able to load most of the way with forge 36.1.31 until it told me that several of the mods needed forge 36.2.4 to load fully. I deleted the profile and restarted the installer with that version of forge and when I tried again it booted me out  mid load with no crash report, only stating "exit code 0"
Any help would be greatly appreciated.

**Comment by fayer3** [comment]
post the latest.log, some mod is causing the crash

**Comment by Espergium** [comment]
I have a hunch that this is Selene crashing. This pack was mentioned in the discord and the log had a selene crash.
http://www.vivecraft.org/forge-mod-compatibility/

**Comment by cgdude1** [comment]
Tried it with the different version of selene in the chart. Got most of the way through the load but it's still just freezing up and refusing to respond.

**Comment by fayer3** [comment]
please post the latest.log

**Comment by Espergium** [comment]
Supply a log. Latest.log from your install directory.

**Comment by cgdude1** [comment]
Sorry, little new to all this where would I find that.

**Comment by cgdude1** [comment]
Is this the correct log or do I need to go searching in the directory again

**Comment by fayer3** [comment]
looks right, I don't see much wrong with it though.
you can try without storagedrawers, that throws some errors,
and advancedRocketry also throws a bunch of errors, if it still doesn't work.

**Comment by cgdude1** [comment]
Interesting, I don't know if it's worth mentioning but when I try and load the pack the boot screen seems like it can't get memory stored as it repeats the same numbers over and over, which is not the case when I load the pack normally.

**Comment by jrbudda** [comment]
could you try again with revision 7 posted today please?

**Comment by cgdude1** [comment]
I am happy to report the pack is loading fine as of right now when installed with revision 7
A huge thank you for helping figure this out.
