### ISSUE TITLE
Installer does not recognize openjdk 16 and 17 executables with zgc option

### ISSUE THREAD

**Issue by takashi1kun** [jrbudda/Vivecraft_116#126]
Data:
OS: Windows 10 x64
Installer used: vivecraft-1.16.5-jrbudda-7-8b-installer.exe

Description:
I tried with that installer using the ZGC option and when it prompts me to select the java executable and i tried to point to the javaw.exe inside the bin inside the installations of OpenJDK of versions 16 and 17, obtained this same day from adoptopenjdk.net and adoptium.net, but it says that those are not java 14+ executables for both, but when i tried with the executable of version 15 it worked.

It seems it is not recognising OpenJDK 16 and 17 executables as ZGC capable, at least the windows 10 x64 current versions.

Not a big problem, as i can just use version 15 but still, I felt like it was good to point it out.

**Comment by takashi1kun** [comment]
I have to add that i was using also the custom forge version and pointing to a modpack directory, i guessed that didn't matter so i did not mention it, but if it servers anything to narrow it down, here is a recreation of the options i had selected

![image](https://user-images.githubusercontent.com/16158418/146671798-0870aec1-1f29-4011-8968-dc0efe93250b.png)

And this is the prompt where it asks me to select the java version.
![image](https://user-images.githubusercontent.com/16158418/146671826-01dbb2d3-4ed5-4f3d-ad0b-84a19e193afb.png)

Images of what openJDK 17 executable i selected
![image](https://user-images.githubusercontent.com/16158418/146671859-04ed374e-d6d3-4b9f-ae57-fb5408a81b4c.png)
![image](https://user-images.githubusercontent.com/16158418/146671868-ad862c2e-9f9f-4e28-8bb2-ca0fd0b8ee4b.png)

And what says when i select it(it says the same with the OpenJDK version 16, but not 15):
![image](https://user-images.githubusercontent.com/16158418/146671882-2d773857-374c-4ad0-a42e-5b6c609b5de8.png)

**Comment by fayer3** [comment]
The issue I think is that 1.16.5 is not fully compatible with java 16+, so it doesn't let you select it.

**Comment by Techjar** [comment]
Yeah, that. There's a specific incompatibility with Forge 1.16.5 that causes it to just crash on Java 16+. You gotta use Java 14/15.
