### ISSUE TITLE
Crash during Mod Deep Scans on Forge 36.2.20

### ISSUE THREAD

**Issue by mmaniac01** [jrbudda/Vivecraft_116#130]
I am using `vivecraft-1.16.5-jrbudda-7-8b-forge` with `Forge-36.2.20`. This modpack was working fine yesterday, and it works fine now with and without OptiFine. However, when I launch it with Vivecraft, I encounter a critical error:

> `Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Multi-argument modifier method drawScreen(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;)V in controllable.mixins.json:client.OptifineGameRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s).`
![image](https://user-images.githubusercontent.com/56617952/155856626-d73124cf-eebb-4f6b-a96f-c8f71c71461c.png)

This occurs several seconds after the "FML Early Loading Process" completes a deep scan of Better Advancements.
It does not generate a crash log. The Minecraft Launcher says:
> Error | **Game Crashed**
> An unexpected issue has occurred and the game has crashed. We're sorry for the inconvenience.
> This crash may be caused by an invalid Java Runtime configuration. Check any custom configuration settings.
![image](https://user-images.githubusercontent.com/56617952/155856600-41dc025e-235e-4641-b6ff-72137c70397d.png)

I have tried running the installation with Java `jdk-15.0.1`, Java `jre-1.8.0_321`, and Eclipse Adoptium `jdk-17.0.2.8-hotspot`.
Adoptium 17 worked yesterday, but not today. I have not added any mods or changed any configurations.

This is really all of the information I can offer, but the entire `latest.log` can be found [here](https://pastebin.com/DBFMJc2g), and a list of mods can be found [here](https://pastebin.com/h0596SiD).

**Comment by fayer3** [comment]
looks like controllable is incompatible with vivecraft.

**Comment by mmaniac01** [comment]
> looks like controllable is incompatible with vivecraft.

I disabled `controllable-0.14.1-1.16.5.jar` and it is no longer crashing. Thank you.
