### ISSUE TITLE
Invisible GUI

### ISSUE THREAD

**Issue by TrentC271** [jrbudda/Vivecraft_116#131]
I was playing Vivecraft just earlier today and realized that I had no gui! I could still interact with everything, and when I open my inventory, I can see my hotbar behind it. Please help!

VERSION: 1.16.5
FORGE VERSION: 36.2.30
MODS: VivecraftForgeExtensions-1.16.4-1.3.3

**Comment by fayer3** [comment]
did you press f1 by accident, or the hide gui option in the settings?

**Comment by Techjar** [comment]
Yeah upon further evaluation, you definitely just hid the HUD by accident. Press F1 or go into VR Settings > HUD and GUI Settings to fix it.

**Comment by TrentC271** [comment]
I didn't hit F1. I made sure of it. Thank you for the advice, though!

**Comment by Techjar** [comment]
To be clear: Vivecraft remembers the hidden state across restarts. It's a feature for certain use cases.
