### ISSUE TITLE
Titanium Library fatal crash

### ISSUE THREAD

**Issue by Steve1150** [jrbudda/Vivecraft_116#138]
The titanium library causes a fatal crash when running with vivecraft

titanium version used: 3.2.8.4

log: https://paste.ee/p/BOMHg

**Comment by fayer3** [comment]
that looks more like an error because you are using java 20.
can you try with the regular java 8

**Comment by Steve1150** [comment]
> that looks more like an error because you are using java 20.
> can you try with the regular java 8

Sorry for the late response.
Could've sworn I'd tried that several times but I tried it again and it worked. Must've just been me.
Thanks for that! And sorry for such a dumb mistake on my part...
