### ISSUE TITLE
[non-vr client] 1.16.3 crash when breaking sugar cane or shift clicking lapis into an enchanting table

### ISSUE THREAD

**Issue by albert-softie** [jrbudda/Vivecraft_116#14]
I was playing on a friend's server which was previously on 1.16.2 before he decided to update to 1.16.3, as well as adding the vivecraft spigot plugin to the server. As such, I decided to create a copy of my 1.16.2 instance in multimc so that I could install the vivecraft novr client on it. 

However, ever since doing so, I found that if I ever try breaking or placing sugar cane anywhere, my game will freeze for a few seconds, cut to a "Saving world..." screen (despite playing on a server), and then crash to desktop. The same thing also happens whenever I attempt to shift click lapis from my inventory into the lapis slot on an enchanting table. I also made sure to disable the "Vivecraft(Forge)" component in my multimc instance settings to confirm whether or not it was the problem, and sure enough it is. 

[Here](https://pastebin.com/QpcqRW2z)'s a crash log for when I tried shift clicking lapis, and [here](https://pastebin.com/59hVnxH7)'s a crash log for when I tried breaking a dirt block that had sugar cane on top of it. 

I'm not sure how much of the info I just gave was actually necessary, but I figured the more info the better.

**Comment by jrbudda** [comment]
i assume this was fixed
