### ISSUE TITLE
Optifine isn't installed 1.18.2

### ISSUE THREAD

**Issue by doggoboiwastaken** [jrbudda/Vivecraft_116#142]
When I add optifine as another mod, the game runs fine in NONVR. However, when I use VR, it crashed. Without added optifine, I have no options for shaders.

**Comment by fayer3** [comment]
1. you are on the 1.16 github.
2. the 1.18.2 installer already includes optifine
3. if you are using the mod from curseforge, that is incompatible with optifine atm, and has an even other github  for issues

**Comment by doggoboiwastaken** [comment]
Thank you for letting me know. I apologize.
