### ISSUE TITLE
Can't build an installer on linux

### ISSUE THREAD

**Issue by flutterbrony** [jrbudda/Vivecraft_116#15]
Hello, I'm trying to use it with my Valve Index on Mint, but when I try to build it, I get en error just after downloading optifine

```
ERROR: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Traceback (most recent call last):
  File "install.py", line 660, in <module>
    main(os.path.abspath(mcp_version))
  File "install.py", line 439, in main
    download_deps( mcp_dir, True, False ) # Vanilla libs
  File "install.py", line 292, in download_deps
    file = os.path.join(jars,"libraries",url.replace("/",os.sep))
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```
I'm using a development version of java, and python 2.7 is installed too

**Comment by TheTrueForce** [comment]
Why are you trying to build the installer? It's just a jar that's been run through Launch4j so people don't try to use it like a Forge mod.

**Comment by flutterbrony** [comment]
I read somewhere that for installing the mod, you have to run install.bat on windows, or install.jar for other os, but there is only an install.sh, install.py, and install.bat, and the .bat and .sh files seems to only run the install.py with python 2.7, correct ?

When I run install.sh, I get the error in the first post.

**Comment by Techjar** [comment]
That's for the dev environment. To just play the mod, download the installer .exe from the releases page and rename it to .jar

**Comment by flutterbrony** [comment]
Thanks ! I tried it, and it work now, I never thought of launching an exe with java, sorry.
But now, it works.

**Comment by Techjar** [comment]
As stated, this is just a special case because the exe is really just a wrapped jar.
