### ISSUE TITLE
wall hax

### ISSUE THREAD

**Issue by LittleBigBug** [jrbudda/Vivecraft_116#16]
The current "anti wall hax" works great! However, you can easily get by this by placing down a stair or something and poke your head through that instead.

Great software, so much fun to mess with!

**Comment by Techjar** [comment]
Yeah, there's not really a good solution for all blocks. The hitboxes don't always match up nicely with the mesh. If you're really worried about people using xray (there's far better ways to get xray than this), install a plugin for it.

**Comment by LittleBigBug** [comment]
Of course! not a problem, I wasn't sure if it was something so easily done. And that is true I didnt think of that, mostly just an oversight on my part! Feel free to keep this issue as reference but I'll close it
Thanks for the quick response, take it easy :)
