### ISSUE TITLE
Vivecraft resets Oculus Rift S

### ISSUE THREAD

**Issue by Cynderblood** [jrbudda/Vivecraft_116#17]
Vivecraft resets my Oculus Rift S to the point that I have to reconnect the USB, as if my PC restarted, I have to reconnect my controllers and go through Guardian setup. All this is not possible while Vivecraft is running in the background, wich makes it impossible to play as the reset happens everytime I start Vivecraft. The 1.15 version worked like a charm

**Comment by Techjar** [comment]
http://www.vivecraft.org/faq/#ocucrash

**Comment by Techjar** [comment]
Try this build: https://cdn.discordapp.com/attachments/195502278508150784/761484140142395392/vivecraft-1.16.3-jrbudda-5-2b-installer.exe

Let us know if that works. If it doesn't, do this: http://www.vivecraft.org/faq/#ocucrash

Please don't try both at once as we want to know if the change in that build actually helps or not. It hasn't been thoroughly tested yet.

**Comment by Cynderblood** [comment]
Sorry for the late reply. It works, but reassigning a button doesn't do anything, as in e.g. "Use" is bound to "Middle Button", but nothing changes in-game. So far I didn't have any crashes.

**Comment by Techjar** [comment]
Vanilla controls have no effect. VR bindings are handled through SteamVR. See this page for more info: http://www.vivecraft.org/vivecraft-steamvr-input/
