### ISSUE TITLE
Will Vivecraft Support Oculus Quest 2 via Oculus Link?

### ISSUE THREAD

**Issue by QPCrummer** [jrbudda/Vivecraft_116#19]
Just wondering. I was going to buy one, but want to make sure it works right!

**Comment by QPCrummer** [comment]
With Oculus Link (Forgot to mention that)

**Comment by QPCrummer** [comment]
Nevermind, I did mention that. I forgot to mention is was the Oculus Link 2.

**Comment by QPCrummer** [comment]
I just read the Emulators, why is the Oculus Link in there? It isn't software, it is a cord. Well, I'm going to close this issue. If anyone was dumb like me and didn't read the Emulators, it will work fine.

**Comment by TheTrueForce** [comment]
Oculus link is exactly the same tech as the steamvr emulators (alvr, virtual desktop) use. It's just sent over the wire instead of wifi.
