### ISSUE TITLE
crash on startup [atio6axx.dll, AMD Driver crash]

### ISSUE THREAD

**Issue by xracecar** [jrbudda/Vivecraft_116#2]
steamvr is open, and then i try to open up vivecraft. a few seconds later in steamvr it crashes and boots me back into steam home.

specs:
Msi B450 Tomahawk
Ryzen 5 3600
32gb lpx vengeance @ 3200mhz C16
XFX Fatboy RX 590 OC+
Oculus Rift S

Crash Log:

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc9aed2e80, pid=2720, tid=6604

 JRE version: Java(TM) SE Runtime Environment (8.0_51-b16) (build 1.8.0_51-b16)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [atio6axx.dll+0xb42e80]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by jrbudda** [comment]
This is covered in the FAQ. Bug in AMD drivers. Downgrade to the recommended version.
