### ISSUE TITLE
[Virustotal.com] McAfee detects one potential threat

### ISSUE THREAD

**Issue by PedroHase** [jrbudda/Vivecraft_116#26]
Hey,

when plugging the `1.16.3 v5`  installer in virustotal.com, McAfee detects one potential threat: https://www.virustotal.com/gui/file/3c5b40c95cbe3e53a6107fba641bf5569070c4c3a94d508dd00a23a3b4c99eb1/detection.

From my research it seems that this is (hopefully) a false positive. I think it would be great to get Vivecraft whitelisted by Mcafee: https://community.mcafee.com/t5/Malware/False-Positive-BehavesLike-Win32-Suspicious-vc/td-p/420276.

Cheers and keep up the great work.

**Comment by Techjar** [comment]
Yeah get right on that, and then be sure to remember to whitelist every new release.

Seriously, I'm of the opinion that this is just not our problem. I don't know why anti-malware throws a shitfit just because we're a Java app, but it's really annoying.

**Comment by Techjar** [comment]
Also, McAfee is garbage, even its original creator and namesake has completely discredited it.

**Comment by PedroHase** [comment]
Completely agree with you. It's just that it could scare users (like myself) on first glance, when not doing some research. Maybe a simply disclaimer on the main page would suffice?

**Comment by PedroHase** [comment]
Maybe to add to that, since Windows Defender also blocks the execution of the installer, would it make sense to [submit the installer to Microsoft](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/submission-guide) to prevent this issue for future users?

**Comment by Techjar** [comment]
Yeah we did that once before, and that worked until we did another release...

**Comment by Alexander01998** [comment]
I once had a similar issue and found that it was because of two method names. For some strange reason, McAfee flags anything as a virus that has methods called `getAttackSpeed()` and `getAttackDamage()`.

Renaming these methods to something else fixes the issue. Maybe Vivecraft also has these method names somewhere?

See this thread for details: https://twitter.com/Wurst_Imperium/status/1229370457838755840

**Comment by Espergium** [comment]
Or just disregard McAfee and get literally any other anti malware. McAfee became the thing it claims to protect against. It's just hot garbage preinstalled on most branded PCs and tries to con people into paying for it.
