### ISSUE TITLE
Crash on Launch on NVIDIA GPU

### ISSUE THREAD

**Issue by ThatBenderGuy** [jrbudda/Vivecraft_116#27]
[launcher_log.txt](https://github.com/jrbudda/Vivecraft_116/files/5489059/launcher_log.txt)
My launcher log is attached.
Forge Version: 34.1.24
MC: 1.16.3
VC: 5-1

Specs:
CPU: Intel Core i7 @ 3.70GHz
RAM: 16GB DDR4
GPU: NVIDIA GeForce RTX 2060 SUPER (4GB)
GPU FW: 452.06

I have this installed on a twitch modpack and it seems to crash at the red screen loading phase. It crashes back to the launcher with the message 
![Capture](https://user-images.githubusercontent.com/3581398/98138580-7c994a00-1e80-11eb-833f-6511387eef04.PNG)

**Comment by GradiusLover2000** [comment]
That forge version is incompatible with vivecraft 1.16.3 until further notice.  Please use a modpack with either an older forge version, or with 1.16.2, 1.16.1 or 1.12.2
