### ISSUE TITLE
Unable to type inside anvil

### ISSUE THREAD

**Issue by Kam1ni** [jrbudda/Vivecraft_116#28]
Renaming stuff inside an anvil does not work at all. The keyboard shows up but none of the keys actually do anything.

**Comment by Techjar** [comment]
wut

**Comment by Kam1ni** [comment]
As I said. When you're in VR, right click on an anvil, place an item inside the first slot and click on the text field. The VR keyboard shows up but none of the keys work. It works in every other place like chat or the menu for example.

**Comment by Techjar** [comment]
That's odd. We're sending key inputs in a pretty generic way so I don't know why the anvil wouldn't be picking it up.

**Comment by Kam1ni** [comment]
I'm pretty sure I'm using it properly. I tried it without vivecraft and it worked. Not using any mods apart from the included version of optifine. I made a video [video](https://www.kami-dev.eu/vivecraft-anvil.mp4) to demonstrate it.

I'm using index controllers though. Maybe something to do with it. But I'm thinking that the field just doesn't get focused when you click on it.

**Comment by Techjar** [comment]
Did you install Vivecraft with Forge or no?

**Comment by Kam1ni** [comment]
I dont think so. It's been a while since I installed vivecraft but I dont see the forge label where it would specify it's version so I assume I didn't.
![image](https://user-images.githubusercontent.com/18658863/98382270-45c35f80-204b-11eb-9b70-495dbc754f87.png)

**Comment by Kam1ni** [comment]
I just installed vivecraft with Forge and the effect is the same. So that's not it.

**Comment by dotcommer** [comment]
> Renaming stuff inside an anvil does not work at all. The keyboard shows up but none of the keys actually do anything.

I don't know if you ever figured this out or not, but for anyone else who comes across this, if you tap "TAB" on the keyboard, it will jump the cursor to the text field.  It should be on there by default, but seems to be somewhere else.  Hope that helps!

**Comment by Techjar** [comment]
Huh that's weird.
