### ISSUE TITLE
Shaders cause inability to swim in water

### ISSUE THREAD

**Issue by SilencedSoppu** [jrbudda/Vivecraft_116#29]
Hello there

Here is how to reproduce the bug.

1. load a shader up in minecraft.
2. quit the game entirely.
3. load minecraft back up and get in game with shaders on.
4. find water and check to see if you can swim.
5. turn off shaders.
6. you should now be unable to swim and ignore all water physics.
7. seems to only be client side, other people see you swimming.

**Comment by jrbudda** [comment]
Thank you. We've been wondering at this bug for a while. This is the best info we've gotten so far to help track it down.

**Comment by jrbudda** [comment]
OK I'm not able to reproduce the bug using the provided steps, so there's more to it:
1) Are you in singleplayer or multiplayer? If multiplayer what type of server.
2) Is this with or without Forge support?
3) What exact version+revision of Vivecraft?

**Comment by SilencedSoppu** [comment]
i was in multiplayer
Nornia.net Vivecraft server 1.16.3
NONVR with forge
vivecraft-1.16.3-jrbudda-NONVR-5-2-forge

**Comment by jrbudda** [comment]
Narrowed down to a bug in the shipped version of Forge with 1.16.3-5r2 VR and NonVR clients.
