### ISSUE TITLE
Vivecraft needs java environment installed despite it already being installed

### ISSUE THREAD

**Issue by gimmeAll** [jrbudda/Vivecraft_116#31]
So I tried to install the vivecraft client, but it asked me to install java environment 1.8.0. I installed it then tried to run the vivecraft program again yet it told me the same thing. I know this question has been asked in the past but I need to know if there is either a better way or something else.

**Comment by gimmeAll** [comment]
Nevermind it just started working after had installing it like 5 times

**Comment by GradiusLover2000** [comment]
You should always restart your machine after Java installs to ensure it makes it into the registry first time.
