### ISSUE TITLE
Question about Integrated Graphics

### ISSUE THREAD

**Issue by yomamaman** [jrbudda/Vivecraft_116#32]
I'm sorry if this isn't allowed here- But I have a question about integrated graphics. I'm going to be getting a new laptop with AMD Radeon Vega 8 graphics, and they're integrated. Does the mod only not work with Intel Integrated Graphics or integrated graphics in general?

**Comment by GradiusLover2000** [comment]
It has been tested thoroughly.  Integrated graphics, both AMD and Intel, cause black screens on VR during play.

**Comment by yomamaman** [comment]
Oh, ok. Thanks

**Comment by yomamaman** [comment]
Actually, I tried this on my Ideapad 3 when it came in and it worked like a charm. No black screens, nada! It's a bit laggy but it still works. Maybe look into AMD further?

**Comment by yomamaman** [comment]
Maybe you didn't test thoroughly enough? But it's ok, I'm happy.
