### ISSUE TITLE
Optifine MD5 bad - downloading 

### ISSUE THREAD

**Issue by LBazowski** [jrbudda/Vivecraft_116#38]
So I have this notification that I getting the download but in fact, the client is not downloading. Please help me resolve this issue as I would like to play Minecraft in VR.
![bad](https://user-images.githubusercontent.com/76094206/102320070-0edd4500-3f39-11eb-80de-34809a861c22.png)

**Comment by LBazowski** [comment]
I found a solution, Just let the downloader sit over night, it should be downloaded by morning.

**Comment by Techjar** [comment]
Yeah this is some kinda networking problem.

**Comment by Xsallys776** [comment]
is there another way?
