### ISSUE TITLE
Smooth autojump

### ISSUE THREAD

**Issue by MerioDev** [jrbudda/Vivecraft_116#39]
I don't like using the button jump so I physically jump to jump in Minecraft. But it gets annoying while scaling hills and plains so what if you had a auto jump feature that treated the blocks like ramps so its more like real life.

**Comment by Techjar** [comment]
This is already a thing? "Walk Up Blocks" should be enabled by default.

**Comment by jrbudda** [comment]
Is steps tho, not ramps. I'm guessing this is the suggestion.
