### ISSUE TITLE
Touch hotbar issue with the context-sensitive click update

### ISSUE THREAD

**Issue by funkyface** [jrbudda/Vivecraft_116#4]
When updating to the 1.16.1 version, the hotbar select has effectively stopped working for me with the Oculus touch controllers. By default the context-sensitive click button in Controls was unmapped and it could not be assigned to a button already in use. Ideally I would like to map it to the place or hit button but this resulted in the button being unusable in-game and marked red in the Controls menu.

Currently the hotbar select has 2 options, ON/OFF. Could there be a third option that supports the previous behaviour? I understand the reason for the change as I've had the accidental select issue myself too but the previous behaviour was more intuitive.

I also haven't used the context-sensitive button before, maybe I'm missing something? Thank you for the update regardless, otherwise it's been working great!

**Comment by Techjar** [comment]
What? The contextual actions are definitely bound by default, to the triggers and grips. They even have their own action set which is hidden by default.

**Comment by Techjar** [comment]
Wait are you looking at the vanilla controls screen? That's completely useless in VR, we don't do stuff there. Bindings are handled by SteanVR.

**Comment by funkyface** [comment]
Yes, my bad, I was looking at the Minecraft controls screen. With default SteamVR settings, should the triggers and grips both work as the contextual click? I tried hovering over the items so that they had the green box around them, but none of the grip or trigger buttons would change to the item, they would just have their default behaviour

**Comment by Techjar** [comment]
Yeah this seems like more of a support issue than an actual bug. Can you come to the Discord server?

**Comment by funkyface** [comment]
The issue was from me having an old custom keybinding preset in SteamVR, "Better Default Controls (No Teleport)" in my case. Changing to the default keybindings fixed all the contextual interactions. Thanks Techjar for the help!
