### ISSUE TITLE
Installer stuck on installing Optifine

### ISSUE THREAD

**Issue by Apacci** [jrbudda/Vivecraft_116#40]
Hey when i want to install vivecraft he stay stuck on installing optifine and nothing happend.

**Comment by Apacci** [comment]
![Sans titre](https://user-images.githubusercontent.com/71091240/102655194-2ce1ba00-4172-11eb-8102-3c5f026becce.png)

**Comment by Sllimeel47** [comment]
I'm having that same problem. Have you figured out how to fix it?

**Comment by HalZheng** [comment]
Same problem.
