### ISSUE TITLE
Controller keeps vibrating

### ISSUE THREAD

**Issue by tehho** [jrbudda/Vivecraft_116#42]
Controller keeps vibrating. Needed to rebind Use/Place to a diffrent button for it to work.
Seams like the scroll is always pressed, no issue in other games.

OS: Pop!_os linux
Valve index and index controllers
SteamVr beta 1.15.15

**Comment by silelmot** [comment]
same here on arch ... any workarounds found but rebinding?

**Comment by Techjar** [comment]
This seems to be a SteamVR bug, but I guess we're the only application actually using a scroll binding.

**Comment by silelmot** [comment]
ok. thanks for this... so i will just remove this binding.

**Comment by jrbudda** [comment]
valve problem

**Comment by mitaka8** [comment]
Where do I rebind the scroll action?  I can't find it anywhere :(

Thanks
