### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by WilliamD47** [jrbudda/Vivecraft_116#43]
Hi i get these errors when running the build.sh or install.sh

`    Extracting native library liblwjgl.dylib
    Extracting native library liblwjgl.dylib.git
    Extracting native library liblwjgl.dylib.sha1
ERROR: 'osx'
Traceback (most recent call last):
  File "install.py", line 660, in <module>
    main(os.path.abspath(mcp_version))
  File "install.py", line 439, in main
    download_deps( mcp_dir, True, False ) # Vanilla libs
  File "install.py", line 264, in download_deps
    url = group.replace(".","/")+ "/"+artifact+"/"+version +"/"+artifact+"-"+version+"-"+lib["natives"][native]+".jar"
KeyError: 'osx'`

Is it compatible with Mac or should I install bootcamp?

**Comment by GradiusLover2000** [comment]
You do not need to rebuild the installer.exe, as it is cross compatible as long as the host system has JVM.

The installer is secretly a .jar wrapped in a .exe.  to attempt to install on mac, use the installer on the download packages page, and rename it from .exe to .jar.  then, with java 8 installed, run it.

**Comment by WilliamD47** [comment]
> You do not need to rebuild the installer.exe, as it is cross compatible as long as the host system has Java.
> 
> The installer is secretly a .jar wrapped in a .exe. to attempt to install on mac, use the installer on the download packages page, and rename it from .exe to .jar. then, with java 8 installed, run it.

Oh thanks so much ill try that now

**Comment by TheTrueForce** [comment]
Are you after the nonVR client or the VR one?
Because SteamVR for Mac had not been updated in years, and had been officially abandoned.

**Comment by WilliamD47** [comment]
Will I still need Windows for SteamVr?

**Comment by GradiusLover2000** [comment]
depends.  we recommend Windows, however.

**Comment by WilliamD47** [comment]
> depends. we recommend Windows, however.

I think im gonna install windows as it saves a lot of time and hassle
