### ISSUE TITLE
Tracking issue occurs when both controllers vibrate

### ISSUE THREAD

**Issue by Xarlasar** [jrbudda/Vivecraft_116#44]
I don't know how to explain it, but whenever something occurs in-game that would cause both of my controllers to vibrate, such as using the bow and arrow, or using the climbeymotion keys to climb walls and use the jump boots, my hands dislodge and fly away from my body. As soon as I end the action that's causing the vibration, my hands snap back to where they should be, and while they're glitching out, the tracking is generally laggy and stutters, aside from the displacement.

Note: I am using an Oculus Rift S, and my game is slightly modded. The mods are as follows:
![image](https://user-images.githubusercontent.com/37159882/103249797-e6911580-493e-11eb-8523-fee157e2891c.png)

**Comment by Techjar** [comment]
Sounds like a problem with the controllers. You should contact Oculus about this. As a temporary workaround you could unbind the haptics in the SteamVR controller bindings menu.

**Comment by Techjar** [comment]
Looks like you aren't the only one with this problem.
https://forums.oculusvr.com/community/discussion/84375/rift-s-controllers-lose-tracking-with-vibration-strong-haptic-feedback
https://www.reddit.com/r/oculus/comments/citwkw/rift_s_controllers_lose_tracking_when_they_vibrate/

There's some seemingly magic fixes in those threads you could try. The most consistent one seems to be using a different USB port (if your motherboard has both USB 3.0 and 3.1 or something like that).

**Comment by Xarlasar** [comment]
Thanks so much for the swift response. Switching out the USB port fixed the issue. I'll close this issue now.
