### ISSUE TITLE
not appearing in vr

### ISSUE THREAD

**Issue by BurroBananas** [jrbudda/Vivecraft_116#46]
I hate this mod 
It doesn't show in my headset and the faq is unhelpful
swapped from amd to nvidia now vivecraft doesn't work 
it only shows on the desktop

**Comment by Techjar** [comment]
Let us see latest.log

**Comment by centerionware** [comment]
My friends and I are having this same issue. I'm on AMD and everything works, He's using an NVidia 2080 super and it won't work. On his desktop he can see the minecraft window, it's responding to the HMD input (can rotate and see his hands, on the monitor) but in steamvr it says 'Javaw waiting...' 
This is his log, which goes on repeating the texture submittion error a ton (built up a 12mb log in just a couple minutes)
https://pastebin.com/str7ujy8

**Comment by centerionware** [comment]
DerTrueForce helped solve it by reverting steamvr and windows mixed reality for steamvr to the non-beta. Thank you!

**Comment by 0Evolve0** [comment]
> DerTrueForce helped solve it by reverting steamvr and windows mixed reality for steamvr to the non-beta. Thank you!

how do i do that?
