### ISSUE TITLE
I am on a laptop 

### ISSUE THREAD

**Issue by AjSmash** [jrbudda/Vivecraft_116#47]
So, I have a laptop that I use my oculus rift s on all the time, and I though maybe minecraft would be cool. So I look up a tutorial and I see vivecraft, and I go ahead and install it. But now whenever I try to boot up the vivecraft installation this message appears "Render setup failed: Intel Integrated Graphics are not supported. If this is a laptop, please force the high preformance GPU. Detected GPU: Intel(R) UHD Graphics." Any Ideas on how to help?
Extras: I have steam vr installed and my laptop is the Predator Helios 3000

**Comment by Techjar** [comment]
http://www.vivecraft.org/faq/#gpu

**Comment by AjSmash** [comment]
worked thank you

**Comment by vinnyg0621** [comment]
I have the same problem!!

**Comment by Kaleidio** [comment]
> I have the same problem!!

read the faq link provided above.

**Comment by Nick-bit-sys** [comment]
I do not know the "Vivecraft folder path" and I cant even find javaw.exe but I installed java. any ideas? same problem btw
