### ISSUE TITLE
OpenJ9 not supported by installer

### ISSUE THREAD

**Issue by thegreatsynan** [jrbudda/Vivecraft_116#50]
I tried updating Vivecraft to 1.16.4 with the installer, but it says that Java isn't installed. I recently swapped to OpenJ9 instead of Hotspot, and Vivecraft was running fine, but the installer refuses to work until I install Hotspot. I was wondering if the installer could recognize OpenJ9 installations as well.

**Comment by Techjar** [comment]
Dunno.

**Comment by Techjar** [comment]
Actually, this just sounds like a problem with launch4j, which is expected since it really knows how to find Oracle JVM installations. Simply renaming the installer from .exe to .jar should work.
