### ISSUE TITLE
Download of the .exe files stall drastically to zero b/s

### ISSUE THREAD

**Issue by LusoH** [jrbudda/Vivecraft_116#52]
I've tried downloading the installer several times now, restarted my internet, pc , used a different browser, but it seems like the download stalls either right after beginning the download, or halfway through. The strange thing even is, that my friend tried it on a completely different computer and had the same problem. This is beginning to get frustrating as similar sized files download immediately and the .Zip folder for the source code downloads just fine.
If you know what's going on, I would appreciate the help as no version of vivecraft seems to be downloadable.
Ps. I'm specifically looking to download version 1.16 of minecraft.

**Comment by LusoH** [comment]
So another friend of me was able to download it and send it to me over discord. I have it now and it works but it is still a mystery why it didn't work for me or my friend.

**Comment by LusoH** [comment]
I'm leaving this open in case anyone has an idea what was going on.

**Comment by Techjar** [comment]
This is a networking issue that's out of our control.

**Comment by LusoH** [comment]
Alright thank you!
