### ISSUE TITLE
Latest Vivecraft 1.16.4 release uses an outdated version of Forge - crashes on launch with most mods

### ISSUE THREAD

**Issue by floral-qua-floral** [jrbudda/Vivecraft_116#55]
Just installed Vivecraft with Forge ([1.16.4 v6 release](https://github.com/jrbudda/Vivecraft_116/releases/tag/1.16.4v6)), and discovered that including any mods crashes the game on startup. Spent a while fiddling around with things, but eventually I found that it looks like it's just Forge 35.0.7 itself, not Vivecraft - it seems to crash on launch with any of the mods I've tested with. It can launch on its own, but as soon as I include any mods it fails to launch. Tested with the following mods individually (only included one at a time) using Forge 35.0.7:
- Antique Atlas 5.4.3
- AutoRegLib 1.6-47
- Biomes O' Plenty 13.0.0.429

However, upon updating to the latest Forge release (1.16.4-35.1.37), I was able to launch with all these mods - so my assumption is just that the Forge version included with Vivecraft's latest release is just too outdated to load these mods.

**Comment by Espergium** [comment]
This is known and pending an update.

**Comment by jrbudda** [comment]
only 1.16.5 gets updates
