### ISSUE TITLE
Vivecraft 1.16.5 - Antialiasing and Antistrophic Filtering Not Working

### ISSUE THREAD

**Issue by nymphlode** [jrbudda/Vivecraft_116#56]
I'm running into an issue where both AA and AF are not working. For anitaliasing, moving the bar anywhere will keep it at 0, while with antistrophic filtering, I can change the value, but it resets to 0 on restart. I tried modifying the Optifine configuration itself to change these values but they reset to 0 no matter what. I'm also keeping in mind that Optifine 1.16.5 HD U G6 comes with the ability to change antistrophic filter and antialiasing and that I've tried it in vanilla +Optifine minecraft without Vivecraft and it has worked as intended.

Any help is appreciated!

Thank you!

**Comment by jrbudda** [comment]
known limitation
