### ISSUE TITLE
[1.16.5] VR rendering issues

### ISSUE THREAD

**Issue by SerizawaX** [jrbudda/Vivecraft_116#58]
![Screenshot (116)](https://user-images.githubusercontent.com/62132224/107200187-f6197900-6a29-11eb-922a-0767369bba20.png)

Both eyes seem to be rendering the exact same image and is very disorienting.

The device is Oculus Quest 1
Issue occurs on both unmodded and modded(forge) versions.

**Comment by Techjar** [comment]
Turn off the shaders, there is a shader pack known to cause this issue.

**Comment by SerizawaX** [comment]
Solved.
