### ISSUE TITLE
[Suggestion] Execute command on first player join as VR.

### ISSUE THREAD

**Issue by TechRoot** [jrbudda/Vivecraft_116#6]
Hello.  I was not able to find a correct way to suggest a feature, so im using this method, hoping you will be able to sort it and  attend it if you agreed to.

In mixed servers, where users may join as desktop or VR, its very usefull to give them certain user role permissions. And to do so automatically, some other plugins specify some options in their config files, where you can specify certain commands to be executed on first join. 

Thanks for your awesome work.

**Comment by Techjar** [comment]
We already have an option to add users to a group through the Vault API.
