### ISSUE TITLE
server init failed(300)

### ISSUE THREAD

**Issue by davo1923** [jrbudda/Vivecraft_116#60]
i just installed the 1.16.6 version on vivecraft but every time I launch I get this error code, any ideas?
(im using oculus quest 2 on virtual desktop )

**Comment by Qardruss** [comment]
Use ALVR and Oculus Link instead

**Comment by papasha1213** [comment]
I have the same error 300, I have Pico 4, global firmware version 5.8.2, I use SteamVR
