### ISSUE TITLE
Quest 2 on Laptop

### ISSUE THREAD

**Issue by DizzyFIy** [jrbudda/Vivecraft_116#62]
I have a "ok" laptop and a Quest 2. I have steam vr and everything but when i open minecraft up on Vivecraft it says render failed error 1114 or something like that. I ordered a USB C to USB A cord and i will let you know if that fixed it. I was attempting wireless but this is okay. 

i will reply or edit this if i get it working..

**Comment by Qardruss** [comment]
If you try wireless, use ALVR, I can't confirm it works myself because it doesn't connect to my Oculus Quest 2
