### ISSUE TITLE
Vivecraft 1.16.5 Not Launching

### ISSUE THREAD

**Issue by PhonieZ** [jrbudda/Vivecraft_116#63]
So it looks like the crash report that something is missing:
[21Feb2021 16:47:21.676] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[21Feb2021 16:47:22.069] [main/ERROR] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Cannot find launch target fmlclient, unable to launch
I tried using a different directory(because I have different directories for different Minecraft versions and mods, don't use multi mc but the vanilla launcher) but it gave the same crash log, so anyone know what I can do? Also I have no mods installed.

**Comment by PhonieZ** [comment]
I also only included the error and warn lines as the other ones just specify how Minecraft was launched

**Comment by DetroitLions904** [comment]
Ya im having the same issue. I was just playing and it was working and it just stopped. Please let me know if you figure it out.

**Comment by PhonieZ** [comment]
oh it looks like iw as using the forge version, for me the non forge version works, so yeah no mods sadly

**Comment by DetroitLions904** [comment]
Ya it worked. Is it an issue on there end?
