### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by blueberry-0** [jrbudda/Vivecraft_116#65]
Using the forge version with vivecraft always seems to crash, i have had the launcher closed while installing, removing certain things and nothing seems to work. I'm assuming it's a problem with the latest version of forge or vivecraft.

**Comment by star-boy-77** [comment]
im having the same problem.

**Comment by Kingfuzzbut** [comment]
Me too. I really wanted to play in my modded world in Vr.
