### ISSUE TITLE
All Versions Say Malware

### ISSUE THREAD

**Issue by CommandBlockGuru** [jrbudda/Vivecraft_116#7]
My computer refuses to let me download Vivecraft on ANY version, not just this one, because it may harm my device. And this isn't just a warning, this is saying that there's actual malware hidden in the file and my computer seems determined to keep it out. I had Vivecraft downloaded before and it gave me absolutely no problem at all, but I had to redownload MC cause the code was messed up or something and now want to be able to play my favorite mods in vr. Please either fix this or tell me what to do. Thank you.

**Comment by Techjar** [comment]
Disable your antivirus or whitelist it, it gets false flagged for some reason, we don't have any control over this.

**Comment by CommandBlockGuru** [comment]
Thank you! I now have Vivecraft installed on my computer and can't wait to play!
