### ISSUE TITLE
Cybershoes support....

### ISSUE THREAD

**Issue by CybershoesVR** [jrbudda/Vivecraft_116#70]
While things are working fine with Vivecraft 1.12.2 (steamVR binding are created, the Cybershoes treadmill is bound to movement/strafing, our driver loads the settings) - no problem, you can walk with your feet.

With Vivecraft 1.16.X not so good. Basically - the same bindings can be applied. But this works only after you've initially started a movement with the hand controller joystick. Then you can use the Cybershoes for walking in all directions and at different speeds. But once you stop, you cannot start moving again unless you trigger this with the joystick. 

Please find here the binding file (txt extension is added because of git)
[org.jrbudda.vivecraft.steamvrinput_cybershoes.json.txt](https://github.com/jrbudda/Vivecraft_116/files/6103046/org.jrbudda.vivecraft.steamvrinput_cybershoes.json.txt)

Any ideas? Our community would be happy if this could be solved. We welcome the developer to outreach to us in order to get a Cybershoes gaming station for testing this.

**Comment by jrbudda** [comment]
this should be fixed.
