### ISSUE TITLE
Won't Install.

### ISSUE THREAD

**Issue by Steven121314** [jrbudda/Vivecraft_116#71]
<img width="488" alt="Installer" src="https://user-images.githubusercontent.com/9997020/112769049-0d69f100-8fed-11eb-89a5-7bbefca71afd.PNG">

When I press the "Install" button, I'm greeted with the "Complete" dialogue instantly, if I move it out of the way, it reveals the progress bar, that does nothing. I waited for an hour and it did nothing, even after closing the "Complete" box. The Minecraft launcher is closed, Steam VR and Oculus are installed and running. What am I doing wrong?

**Comment by Techjar** [comment]
Please run the installer from the command line with `java -jar name-of-installer.exe` and provide us with whatever it outputs to the command prompt window.

**Comment by Steven121314** [comment]
It ran, but didn't output anything
<img width="487" alt="bruh" src="https://user-images.githubusercontent.com/9997020/112769548-b0bc0580-8fef-11eb-91c2-8478cc4ecbd2.PNG">

**Comment by Techjar** [comment]
You clicked install like before?

**Comment by Steven121314** [comment]
Yes, and it did the exact same thing as before

**Comment by Techjar** [comment]
Have you tried redownloading the installer?

**Comment by Steven121314** [comment]
Yes, I even tried the 1.16.4 installer, and also tried changing the extension to .jar

**Comment by Steven121314** [comment]
Java 16

**Comment by Techjar** [comment]
Oh, Java 16 is broken with Vivecraft. Get Java 14 instead.

**Comment by Steven121314** [comment]
I went down to 15.0.2, I have another program that needs at least 15. The installer ran perfectly. Thank you!

**Comment by Techjar** [comment]
Alright, well for the record if you want to use ZGC with Vivecraft, you still need Java 14. Multiple versions can co-exist, just untick the option for setting it as the new default JVM.
