### ISSUE TITLE
Incorrect parts of skin used for shoulders and hands.

### ISSUE THREAD

**Issue by Orangestar12** [jrbudda/Vivecraft_116#74]
For VR players, the mod does not seem to be using the correct portions of the skin for "shoulders" and hands.

A render of my skin:
![image](https://user-images.githubusercontent.com/785315/115257673-eab38f80-a0f5-11eb-8931-091ac32921ff.png)

A screenshot taken by a friend (using shaders and a resource pack):
![image](https://user-images.githubusercontent.com/785315/115257630-e0919100-a0f5-11eb-9d33-5e1b9702b71b.png)

The pieces don't seem to line up at all.

**Comment by Nathan22211** [comment]
maybe without the shaders? the rain is warping the model a bit

**Comment by jrbudda** [comment]
this has been addressed in newer versions of Vivecraft, unlikely to be backported to 1.16
