### ISSUE TITLE
Corrupt JAR file for Forge installation

### ISSUE THREAD

**Issue by Boefjim** [jrbudda/Vivecraft_116#75]
I keep getting a corrupt JAR file whenever I try to install Vivecraft with Forge support
![image](https://user-images.githubusercontent.com/16748131/115362269-a55c9400-a1c1-11eb-9fa6-137f020d9f44.png)
Any idea why that might be the case?
I already tried using Vivecraft v6 instead of v7, and tried to install different versions of Forge, but I still get the same message...

**Comment by Techjar** [comment]
Manually download and install Forge 36.0.1. Seems like there's some sort of networking issue going on, we're not sure at the moment.

**Comment by Techjar** [comment]
Forge has changed the URL. Great. Fuck you guys.

**Comment by sicklybeans** [comment]
> 
> 
> Manually download and install Forge 36.0.1. Seems like there's some sort of networking issue going on, though we're not sure at the moment.

I'm having this problem as well. I tried installing forge manually but it just creates a profile parallel to the vivecraft one. In other words, I can install forge and i can install vivecraft but I'm not sure how to install both
