### ISSUE TITLE
Idea for easier usage with Controllers

### ISSUE THREAD

**Issue by DrakenRolle** [jrbudda/Vivecraft_116#77]
My idea is, add some kind of an option to the seated options, which set the Cross always centered in screen mid (Just like in Normal minecraft). this would make the controls for this way easier.
So if you in example move stick right -> right Mouse move -> Move the Camerea/head to the right.

Now it moves the Cross to the border and then beginns the movement. This works well with the VR controllers, but with this simple option gamepads would work so much better in this setup.

**Comment by Techjar** [comment]
Setting the keyhole to 0 should work.
