### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by Johnorable** [jrbudda/Vivecraft_116#78]
Hey, just tried to install vivecraft (fresh mc download, default installer settings, even tried with admin perms) to no avail.
It just instantly pops up with this (progress window will infinitely 'install', no files actually changed).
Notably, just updated to new JRE version (20/4/21)

[Screenshot](https://prnt.sc/11t7gat)

**Comment by MeowMC** [comment]
don't use Java 16
