### ISSUE TITLE
My Pc AND Antivirus says its a ransomware or virus, is this actually true? im scared lol

### ISSUE THREAD

**Issue by epicOswald123** [jrbudda/Vivecraft_116#79]

**Comment by Techjar** [comment]
What? No of course Vivecraft isn't malware, it's just a false positive. What anti-malware is telling you this anyways?

**Comment by epicOswald123** [comment]
> What? No of course Vivecraft isn't malware, that's just a false positive (assuming you got it from here and not some other sketchy site). What anti-malware is telling you this anyways?

Windows defender + Trend Micro Security. I already opened it so its fine now but thanks :)

**Comment by Techjar** [comment]
Yeah I don't know why everything has a hissy fit over the launch4j wrapper. We're working on a new solution though, so hopefully this will less of a problem in the future.
