### ISSUE TITLE
Modded weapons show up small

### ISSUE THREAD

**Issue by Boba194230** [jrbudda/Vivecraft_116#80]
I'm using the tetra mod and everything seems to work except after I edit an item it won't show up as the normal size anymore. I'm thinking it might be the same case with tinkerer's construct as well but idk.

**Comment by Boba194230** [comment]
yeah i just tested it with tinkerer's construct items and they show up small too. Is there any way to whitelist those items so they show up big or by a weapon class or something?

**Comment by jrbudda** [comment]
mod item rendering is the bane of my existance.
