### ISSUE TITLE
SteamVR Crashing when opening game or loading into singleplayer world

### ISSUE THREAD

**Issue by randomman254** [jrbudda/Vivecraft_116#83]
For some reason sometimes SteamVR completely crashes when I either load into singleplayer, or just open the game. Multiplayer is unaffected and I can load into that just fine without crashing.

Crash log from loading into singleplayer: [crash-2021-04-29_13.38.15-client.txt](https://github.com/jrbudda/Vivecraft_116/files/6437878/crash-2021-04-29_13.38.15-client.txt)

**Comment by Techjar** [comment]
Sounds like your CPU might be getting overloaded. If you're on Oculus, there's a workaround for this in the FAQ: http://www.vivecraft.org/faq/#ocucrash

**Comment by randomman254** [comment]
I can't access the vivecraft.org website. It appears as a 404 for me.

**Comment by Techjar** [comment]
That's weird. You sure you're at the right link?

**Comment by randomman254** [comment]
Yes. It seems to be working now today. I'll try what was given in that FAQ and leave and update with how it goes.

**Comment by randomman254** [comment]
After more research and also forgetting to mention I have an Index (meaning oculus workarounds likely won't help me) I'm just going to close the issue and figure this out on my own or just upgrade my subpar CPU.
