### ISSUE TITLE
Controllers not working

### ISSUE THREAD

**Issue by d370** [jrbudda/Vivecraft_116#87]
i am trying to play on oculus quest using virtual desktop. When i start the game it shows my hands on the ground under me and i can not move them. they are just stuck. other games recognize the controllers though so i just think it vivecraft.

**Comment by jrbudda** [comment]
user setup issue

**Comment by Chizza123** [comment]
> user setup issue

What can I do to fix it? I've already wiped and deleted and reinstalled forge and minecraft but it still doesn't work.
