### ISSUE TITLE
Option to not fully override launch arguments

### ISSUE THREAD

**Issue by ghost-420** [jrbudda/Vivecraft_116#89]
https://github.com/jrbudda/Vivecraft_116/blob/master/installer/Installer.java#L1395
> **Only `-Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true` is required to be set, so continue to do.**

I use the following launch arguments I conjured up around 2 to 3 years ago to make the Minecraft client much smoother (not suitable for servers), and I still not have found launch arguments that beat this out on a AMD Ryzen 9 3900x (& Intel i7 6700k) with a nVidia 1080 Ti:
```
-Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSScavengeBeforeRemark -XX:+DisableExplicitGC -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:TargetSurvivorRatio=90 -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true
```

**Comment by jrbudda** [comment]
unticking the 'create/update profile' checkbox should keep your options intact

**Comment by Techjar** [comment]
ZGC is better.
