### ISSUE TITLE
Multuple issues trying to run vivecraft 1.16.5 with forge

### ISSUE THREAD

**Issue by Nathan22211** [jrbudda/Vivecraft_116#90]
I've tried with the normal launcher, twice, and both times the install either errored midway through or said that forge was corrupted. In multiMC it seemed to work fine, but it still doesn't work and I get this in the log https://gist.github.com/Nathan22211/848626e082cdf4bce98009172dfd02da

**Comment by Techjar** [comment]
This looks like the kinda shit that happens when the version items aren't in the correct order. Did you follow the instructions at http://www.vivecraft.org/multimc/ exactly?

**Comment by Nathan22211** [comment]
I did, other than changing the used forge version to a newer one, but I had issues with the normal MC launcher too when trying to install it with forge, so it's not limited to MultiMC

**Comment by Nathan22211** [comment]
could this still be an issue? https://github.com/jrbudda/Vivecraft_116/issues/75 I had that happen to me at one point trying to install it

**Comment by Techjar** [comment]
Nah that should be fixed.

**Comment by Nathan22211** [comment]
wait no, I must've skipped over forge being installed before vivecraft. But that doesn't help explain why the vanilla launcher was having issues

**Comment by Techjar** [comment]
Yeah we definitely fixed the Forge installation issues, so I'm not really sure what's going on in your case.
