### ISSUE TITLE
Unable to find OpenJDK

### ISSUE THREAD

**Issue by prdoyle** [jrbudda/Vivecraft_116#92]
The installer claims I have no Java installed and takes me to the Oracle Java download page. But I have OpenJDK 8 installed and it's on my path. I'm running Windows 10.

How does the installer locate Java? Is it `JAVA_HOME`? If so, it would be helpful if the error message described this so the user can fix it.

**Comment by prdoyle** [comment]
I had a JRE with `PATH` pointing to the `bin` directory. No dice.

I downloaded a JDK and pointer `PATH` to the `bin` directory. No dice.

I pointed `JAVA_HOME` to the main directory. No dice.

I wish I knew what the installer was looking for.

**Comment by Sacryn** [comment]
I've gone through the same procedure. Still just errors out and opens the Oracle JRE download page. I'm guessing its looking for some kind of registry key instead of JAVA_HOME and/or simply running java -version to check current installed version.

**Comment by Techjar** [comment]
Just rename the installer from .exe to .jar if the wrapper can't find Java.

**Comment by Sacryn** [comment]
I made a java.reg file with the following entries:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft]

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit]
"CurrentVersion"="16"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\16]
"JavaHome"="C:\\Program Files\\Java\\jdk-16.0.1"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment]
"CurrentVersion"="16"

[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment\16]
"JavaHome"="C:\\Program Files\\Java\\jdk-16.0.1"
```

Solved the issue. Apparently the wrapper only uses registry entries from Oracles installer to find your Java installation instead of using the JAVA_HOME env-variable. Just change the version and path in the example above to match your OpenJDK installation

**Comment by Techjar** [comment]
You... do realize you don't need to do that manually right? The AdoptOpenJDK installer has options for this.
![](https://qimg.techjargaming.com/i/Iln3AOhq.png)

**Comment by Sacryn** [comment]
> You... do realize you don't need to do that manually right? The AdoptOpenJDK installer has options for this.

Personally, I've never heard of AdoptOpenJDK before. I usually install grab a .zip directly from [](https://jdk.java.net/ as instructed) from [](https://openjdk.java.net/install/index.html). Adding a JAVA_HOME check in `installer/launch4j/head_src/head.c` should not be super hard. At least as a fallback if all registry checks fail.

**Comment by Techjar** [comment]
Oh, well, I can recommend AdoptOpenJDK as it's basically the exact same thing as that .zip, but packaged up into a nice convenient installer.

**Comment by jrbudda** [comment]
jarfix usually fixes this kind of thing too
