### ISSUE TITLE
Add "Only" option to all roomscale options

### ISSUE THREAD

**Issue by matejdro** [jrbudda/Vivecraft_116#95]
At the moment all roomscale options (ladders, swimming etc.) are either Off on On. To increase immersion, I propose third option: Only

This option would would disable regular non-roomscale interaction and would force player to use room scale option. For example, if "Roomscale climbing" is set to "Only", player would not be able to climb by walking forward into a ladder (and drop down by just being on a ladder). He/she would have to move the hands.

**Comment by Techjar** [comment]
Not really viable as not everything is actually hooked up to roomscale interactions, and for some of them both the controller input and the roomscale part have uses, so it wouldn't make sense to have an "only" option there.

Just enforce some self restraint. :)

**Comment by matejdro** [comment]
Hm, I see. Should I close this then?
