### ISSUE TITLE
black picture frame when I change settings?

### ISSUE THREAD

**Issue by SnowRat123** [jrbudda/Vivecraft_116#96]
Hi, ive been playing vivecraft for a while and have really enjoyed it. Vivecraft adds a whole new level of immersion and interest to a game i have played all my life.

Recently I have encountered and error where if i change any settings or I accidentally forget to turn off shaders before loading the game a black picture frame appears around the edge of my vision and it becomes almost impossible to play as i feel like i have been trapped in a box.

The only way i have found to rid myself of this box is to reload the game which is very annoying especially when i am playing multiplayer.

Thank you for creating this amazing mod and i appreciate any help that you can provide
![OculusScreenshot1622629018](https://user-images.githubusercontent.com/85226875/120464140-85111f00-c394-11eb-879f-e855f186e36a.jpeg)

**Comment by Techjar** [comment]
Can you provide a screenshot?

**Comment by Techjar** [comment]
Uh... that's definitely not supposed to happen. Can you please upload latest.log from .minecraft/logs?

**Comment by SnowRat123** [comment]
the one thats just called 'latest'?

**Comment by Techjar** [comment]
Yeah.

**Comment by SnowRat123** [comment]
also, thank you for taking time out of your day to help me

**Comment by Techjar** [comment]
Yeah I'm not sure what's going on there. Seems like maybe a driver bug or something, possibly caused by the combination of shaders and your particular GPU? (750 Ti, ouch)

**Comment by SnowRat123** [comment]
yeah i thought that, but its never happened before

**Comment by Techjar** [comment]
Does it only happen with the shaders on?

**Comment by SnowRat123** [comment]
no it happens without shaders when i change any settings

**Comment by Techjar** [comment]
Ah. That is very strange. Can you try updating your graphics driver?

**Comment by SnowRat123** [comment]
Ill try that now, thanks

**Comment by SnowRat123** [comment]
i just wish the graphics card prices hadn't shot up, the prices are crazy

**Comment by Techjar** [comment]
Yeah... at least you're not stuck with craptastic integrated graphics.

**Comment by SnowRat123** [comment]
yeah the 750 ti can actually run most new game, you just have to be used to bad graphics

**Comment by SnowRat123** [comment]
sadly, updating my drivers didnt help, but 1. its not game-breaking, its just slightly annoying and 2. im sure updating my drivers helped solve many other problems so thank you

**Comment by Techjar** [comment]
Hmm. Alright, I'll see if I can reproduce this later.

**Comment by jrbudda** [comment]
is this still a problem?

**Comment by SnowRat123** [comment]
No, but thank you for showing concern
